trigger: none
  # branches:
  #   include:
  #     - main  # or your deployment branch

variables:
  terraformVersion: '1.6.6'
  azureServiceConnection: '6f0f938c-0599-4b69-9b56-09468ec24549'
  environment: 'dev'

stages:
  - stage: Terraform_Deploy
    displayName: 'Terraform Deployment'
    jobs:
      - job: Terraform
        displayName: 'Terraform Init, Plan and Apply'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UseTerraform@0
            inputs:
              terraformVersion: '$(terraformVersion)'

          - checkout: self

          - task: AzureCLI@2
            name: azLogin
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logged into Azure via service connection."

          - script: |
              terraform init -backend-config="key=$(environment).tfstate"
            displayName: 'Terraform Init'

          - script: |
              terraform validate
            displayName: 'Terraform Validate'

          - script: |
              terraform plan -out=tfplan -input=false
            displayName: 'Terraform Plan'

          - task: ManualValidation@0
            inputs:
              instructions: 'Approve to apply Terraform changes in $(environment)'
              onTimeout: 'reject'
              timeout: '1d'
            displayName: 'Manual Approval (Optional)'

          - script: |
              terraform apply tfplan
            displayName: 'Terraform Apply'
